### ISSUE TITLE
Where should I specify the label count? I can only see maxlabelcount inside startaxis. Thanks

### ISSUE THREAD

**Issue by mikfas** [patrykandpatrick/vico#220] opened 2023-03-23 12:59 UTC
Where should I specify the label count? I can only see maxlabelcount inside startaxis. Thanks

_Originally posted by @mikfas in https://github.com/patrykandpatrick/vico/issues/194#issuecomment-1481149998_

**Comment by patrickmichalik** [comment] 2023-03-23 14:07
I’ll be closing this issue because it’s a duplicate of your comment under issue #194. I’ve responded there.

**Closed by patrickmichalik** 2023-03-23 14:07 UTC
