### ISSUE TITLE
Bug: entryLocationMap disconnect with multiple charts on tablets

### ISSUE THREAD

**Issue by bryantJB** [patrykandpatrick/vico#193] opened 2023-03-03 17:09 UTC
The `x` values used for the `key` values of `entryLocationMap` are calculated differently between `LineChart` and `ColumnChart`. On larger devices (i.e tablets or foldable phones), this causes a slight math/rounding errors and the `key` values end up being slightly different (like 0.0001f). I have not seen this issue on smaller devices. 

I am using compose with a `ColumnChart` with two values stacked and one `LineChart` with single values.
As you can see in the screenshot below, instead of 1 entry location for a with size 3 (one for `LineChart`, two for `ColumnChart`), we sometimes get an entry location for `LineChart` (size 1) and a separate one for `ColumnChart` (size 2) with `keys` very similar but rounded slightly differently.

I suggest a rounding to each value (`floor` to whole pixel maybe?) to force a consistency in `key/x` values

<img width="793" alt="Screen Shot 2023-03-03 at 11 11 16 AM" src="https://user-images.githubusercontent.com/126901486/222778179-42e223a9-caf9-4208-8ff5-a28fe12ba762.png">

**Comment by patrickmichalik** [comment] 2023-03-03 18:26
Thanks for the detailed bug report! We’ll look into this.

**Comment by patrickmichalik** [comment] 2023-04-09 11:54
Hello! Unfortunately, we’re having trouble reproducing this. Would you be able to provide a minimal reproducible example, as well as information on your device’s screen, so we can create a comparable AVD? Cheers!

**Comment by bryantJB** [comment] 2023-04-11 14:25
I narrowed it down to a math issue specifically happening in the `ColumnChart` portion (the .1 + .2 = .30000004 bug that's so popular). I haven't been able to replicate it in a new app or your sample app either so I'm going to look more into my data and customizations then update if I figure it out.

**Comment by patrickmichalik** [comment] 2023-04-13 15:18
Got it. Thanks!

**Comment by bryantJB** [comment] 2023-06-09 18:10
As a quick update: We were able to get the issue to go away but I'm not 100% sure what we did lol My theory is that we may have inadvertently caused an odd number in our chart size with our padding and/or chart data (which was using up to a full years of data but would produce an odd number of months if there were only say 5 months of data)

**Comment by patrickmichalik** [comment] 2023-06-12 06:43
Thanks for the update! I’m glad the issue is gone. Since we’re not able to reproduce the problem, I’ll be closing this issue. Should it reappear, please feel free to reopen the issue.

**Closed** 2023-06-12 06:43 UTC
Labels: bug
