### ISSUE TITLE
Line Chart fails silently

### ISSUE THREAD

**Issue by NunoPalma** [patrykandpatrick/vico#396] opened 2023-09-11 18:55 UTC
**Describe the bug**
```
 val xValues = listOf(500f, 1799.6425f, 1800.622f, 1801.6012f, 1802.5796f, 1803.5577f, 1804.535f, 1805.5118f)
//  val xValues2 = listOf(500f, 1799.6577f, 1800.677f, 1801.6266f, 1802.5616f, 1803.6617f, 1804.666f, 1805.5123f)
val yValues = listOf(1f, 0.22f, 1f, 0.1f, 3f, 5f, 1.22f, 2f)


val floatEntryList = xValues.zip(yValues) { x, y ->
                    FloatEntry(x, y)
 }
 
Chart(
chart = lineChart(),
 chartScrollSpec = rememberChartScrollSpec(isScrollEnabled = false),
model = entryModelOf(floatEntryList),
startAxis = rememberStartAxis(),
bottomAxis = rememberBottomAxis(),
horizontalLayout = HorizontalLayout.FullWidth(),
)
```

# Output from using xValues

![Screenshot 2023-09-11 193907](https://github.com/patrykandpatrick/vico/assets/25639218/e5262ea3-000d-44af-b99d-206d6f17a1cf)

# Output from using xValues2

![Screenshot 2023-09-11 194553](https://github.com/patrykandpatrick/vico/assets/25639218/c7fcec9b-303e-46df-8b57-ab41e3ab2bae)

---
I am working with some rather large datasets with high precision, I initially assumed the issue could be somewhat related to the precision as mentioned here https://github.com/patrykandpatrick/vico/issues/374 but even if the precision is decreased to, let's say, one floating point - this issue still happens. Nothing is rendered and no error is thrown.

---

**Module**
- [ ] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [X ] `compose-m3`
- [ ] `core` (select if none of the above apply)

**To reproduce**
Preview the sample code.

**Expected behavior**
Chart would be rendered, or a concrete error would be thrown.

**Android versions**
Android 9, 10, 11, 12, 12L

**Comment by patrickmichalik** [comment] 2023-09-11 20:27
Hello! Thanks for the report. Since, as I’ve described under #374, two decimal places are the limit for the precision of _x_ values, could you please provide an example where this limit isn’t exceeded, but unexpected behavior occurs? You’ve mentioned that the issue persists with _x_ values whose precision is a single decimal place—could you share those _x_ values? On my end, with such values, everything seems to work properly. Without this change, I get a crash, not an empty chart, but precision issues may manifest themselves in many different ways. With `xValues2`, I’ve not been able to observe anything unexpected, but once again, with more than two decimal places of precision, inconsistent behavior may occur. Cheers!

**Comment by patrickmichalik** [comment] 2023-09-22 16:10
Due to the lack of an example where the precision of the _x_ values doesn’t exceed the recommended two decimal places, I’ll be closing this issue for now. Please feel free to provide such an example and reopen the issue. Cheers!

**Closed by patrickmichalik** 2023-09-22 16:10 UTC
Labels: bug
