### ISSUE TITLE
chart label is not drawn inspite of having ample space

### ISSUE THREAD

**Issue by rupeshjainearnin** [patrykandpatrick/vico#255] opened 2023-05-09 22:17 UTC
**Describe the bug**
chart label is not drawn inspite of having ample space

**Module**

- [ x] `compose`
- [ x] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [x ] `core` (select if none of the above apply)

**To reproduce**
Create a chart with two data points and spacing of 30
x axis is Epoch days since 1970
y axis any value between 500-800
tickPosition = HorizontalAxis.TickPosition.Center

**Expected behavior**
labels should be drawn correctly

**Screenshots**
<img width="482" alt="Screenshot 2023-05-09 at 3 12 39 PM" src="https://github.com/patrykandpatrick/vico/assets/78571048/c6f86dfd-79ab-4996-96b0-0c5ffc45c87e">

**Android versions**
Versions of Android where the bug occurs.

**Additional context**

**Comment by patrickmichalik** [comment] 2023-05-10 04:33
Hello! Would you be able to provide a minimal reproducible example?

**Comment by rupeshjainearnin** [comment] 2023-05-12 19:06
Sure

This is the data you need to add 

//raw data from BE
     listOf(
         "2022-07-14" to 350f,

         "2022-08-14" to 654f,
}


//ChartEntryModelProducer
ChartEntryModelProducer {
        data.map { (y, dateString) ->
            FloatEntry(
                LocalDate.parse(dateString?.truncateDate()).toEpochDay().toFloat(),
                y?.toFloat() ?: 0f,
            )
        }
            .let {
                return ChartEntryModelProducer(it)
            }
    }

//xaxis configuration
  val axisValueFormatter =
        AxisValueFormatter<AxisPosition.Horizontal.Bottom> { value, _ ->
            LocalDate.ofEpochDay(value.toLong()).month.getDisplayName(
                TextStyle.SHORT,
                Locale.getDefault(),
            )
        }


      bottomAxis = bottomAxis(
                        label = axisLabelComponent(
                            color = colorResource(id = R.color.content_fill),
                            textSize = 16.sp,
                            typeface = Typeface.DEFAULT,
                            horizontalMargin = 5.dp,
                        ),
                        valueFormatter = axisValueFormatter,
                        guideline = null,
                        tick = null,
                        tickPosition = HorizontalAxis.TickPosition.Center(
                            0,
                            NUMBER_OF_DAYS_IN_MONTH,
                        ),
                    )


Please let me know if you need anything else

**Comment by patrickmichalik** [comment] 2023-05-15 16:18
Thank you! `TickPosition.Center#spacing` isn’t necessarily the difference between the _x_ values corresponding to two neighboring labels. To determine this difference, one must multiply the value of `TickPosition.Center#spacing` by the _x_ step. In your chart, the _x_ step is 30, and the difference is 30 squared, which is 900. Please try leaving `TickPosition.Center#spacing` at the default value of 1. Both labels will then be visible.

**Comment by rupeshjainearnin** [comment] 2023-05-19 22:02
if there are three data points the labels appear without changing anything else..


I want to display month (Jan, Feb, March and so on)..if I get two values in say Jan I want to display Jan only once on the xaxis..if I leave the spacing to default 1 it displays Jan multiple times..

Can you please reopen the bug

**Comment by patrickmichalik** [comment] 2023-05-21 16:46
Thank you for the clarification. We’re currently working on a new API that’ll make this (among other things) possible—I’ll let you know once it’s available. Even so, the current behavior is expected and doesn’t constitute a bug. The issue remains open, but I will be adding the “enhancement” label, not the “bug” label.

**Comment by rupeshjainearnin** [comment] 2023-05-31 21:36
Thank you.Please fix asap.

**Comment by rupeshjainearnin** [comment] 2023-06-29 21:36
@patrickmichalik  how is it not a bug when you can clearly see there is space to draw the label..Can you please mark these as a bug

**Comment by patrickmichalik** [comment] 2023-07-03 10:42
Several conditions must be met for a label to be drawn. Here, they’re not met, and so no there’s no label—`HorizontalAxis` is behaving as expected and as documented. We’re working on making the API more flexible, but the behavior described here isn’t out of the ordinary, and so it doesn’t constitute a bug. Please rest assured that how this issue is labeled has no bearing on our work on the API changes that I’ve mentioned.

**Comment by patrickmichalik** [comment] 2023-07-03 15:43
[Vico 1.7.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.7.0) introduces the improvements mentioned. My suggestion would be to set the _x_ step to 1 and normalize your entries’ _x_ values such that the first day of every month corresponds to a whole number _n_, and the subsequent days correspond to values in the (_n_, _n_ + 1) interval.

**Comment by patrickmichalik** [comment] 2023-07-25 17:43
The changes introduced in [Vico 1.7.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.7.0), [1.7.1](https://github.com/patrykandpatrick/vico/releases/tag/v1.7.1), and [1.7.2](https://github.com/patrykandpatrick/vico/releases/tag/v1.7.2) should enable you to achieve the result you’re looking for. `getXStep` lets you lock the _x_ step, and thanks to `AxisItemPlacer.Horizontal`, you have full control over what _x_ values labels are displayed for.

**Comment by praveenathuru** [comment] 2023-09-13 10:38
@patrickmichalik Can you please provide a solution for this? I have a similar requirement where I need to plot all values for both x and y axes, with x representing the months. I followed this [link](https://patrykandpatrick.com/vico/wiki/axes/#formatting-axis-values), and the chart is drawing fine. There are endless duplicate month names displayed at the bottom. Please provide a way to display only a single month with multiple values on the chart.

**Comment by patrickmichalik** [comment] 2023-09-17 15:03
@praveenathuru, as mentioned above, you can use `AxisItemPlacer.Horizontal` to achieve this. `getLabelValues` lets you specify which _x_ values are to be labeled. The `spacing` parameter of `AxisItemPlacer.Horizontal.default` is insufficient here because months differ in length. You could use `spacing` if you wanted the labels to be equally spaced. You’d then have to normalize the _x_ values accordingly.

**Comment by patrickmichalik** [comment] 2023-09-24 17:56
Since it’s now possible to achieve the result described here, I’ll be closing this as completed.

**Closed by patrickmichalik** 2023-09-24 17:56 UTC
Labels: enhancement
