### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'float com.patrykandpatrick.vico.core.entry.ChartEntry.getX()' on a null object reference

### ISSUE THREAD

**Issue by subhashisbhowmik** [patrykandpatrick/vico#408] opened 2023-09-25 03:03 UTC
**Describe the bug**
Version: 1.9.2 (Unable to try newer versions due to #407)

Usage:
```
    private val producer = ChartEntryModelProducer()

```
```
LaunchedEffect(key1 = Unit) {
    while (true) {
        producer.setEntries(viewModel.dataList)
        delay(500)
    }
}
VicoChart(producer = producer)
```
```
@Composable
    fun VicoChart(producer: ChartEntryModelProducer) {
        Chart(
            chart = lineChart(),
            chartModelProducer = producer,
            startAxis = rememberStartAxis(),
            bottomAxis = rememberBottomAxis(),
            diffAnimationSpec = snap()
        ) {
            3F
        }
    }
```

The `dataList` is being updated by a flow collector:
```
f.collect { data ->
    viewModel.dataList.add(FloatEntry(data.t.toFloat()/256F,data.t.toFloat()))
    while (viewModel.dataList.size> BUFFER_SIZE) viewModel.dataList.removeFirst()
}
```
This issue is not occurring immediately, but after around 10-15s. `BUFFER_SIZE=3840` 
The issue occurs after ~7k data points.

```
java.lang.NullPointerException: Attempt to invoke interface method 'float com.patrykandpatrick.vico.core.entry.ChartEntry.getX()' on a null object reference
	at com.patrykandpatrick.vico.core.entry.diff.DefaultDiffProcessor.updateProgressMap(DefaultDiffProcessor.kt:101)
	at com.patrykandpatrick.vico.core.entry.diff.DefaultDiffProcessor.setEntries(DefaultDiffProcessor.kt:47)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.setEntries$lambda$1$lambda$0(ChartEntryModelProducer.kt:77)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.$r8$lambda$DLLZQwVnv6C3LZjvqE_A2NZ0Tws(Unknown Source:0)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer$$ExternalSyntheticLambda1.run(Unknown Source:8)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Module**

- [x] `compose`
- [x] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [x] `core` (select if none of the above apply)

**To reproduce**
Unsure, try rendering a timeseries data and trim it from the end to a fixed length. Render it every 500ms.

**Expected behavior**
No error

**Screenshots**
N/A

**Android versions**
13

**Additional context**
N/A

**Comment by subhashisbhowmik** [comment] 2023-09-25 03:21
Okay looks like the issue is here: 
```
viewModel.dataList.add(FloatEntry(data.t.toFloat()/256F,data.t.toFloat()))
```

There seems to be an upper bound in the y axis data here.  Not sure how this is causing an NPE in the end though. I'll see if I can add some error handlers in the coroutine and figure this out.

**Comment by subhashisbhowmik** [comment] 2023-09-25 08:26
Update: With this case as well I am facing the same issue after quite a while. I'm not sure what's causing it, and seems hard to reproduce.

**Comment by subhashisbhowmik** [comment] 2023-09-25 10:14
in `DefaultDiffProcessor.kt`:
```
newEntries
                .getOrNull(i)
                ?.forEach { chartEntry ->
                    map[chartEntry.x] = ChartEntryProgressModel(
                        oldY = map[chartEntry.x]?.oldY,
                        newY = chartEntry.y,
                        temporary = false,
                        chartEntry = chartEntry,
                    )
                }
```
and `i` can go upto `val maxListSize = maxOf(oldEntries.size, newEntries.size)` which seems like a bad idea when paired with `.getOrNull(i)` 

Any clue why this was done this way?

I do not require any animation, can I bypass this `diffProcessor`? Anything I might be doing wrong? From my code the `newEntries` and `oldEntries` should have the same size of BUFFER_SIZE when the error occurs, not sure what is going on.

**Comment by patrickmichalik** [comment] 2023-09-25 15:47
Yup, let’s talk there until that issue is resolved.

**Comment by subhashisbhowmik** [comment] 2023-09-25 16:09
So now the issue I'm facing after upgrading to 1.13.0-alpha.2 is an immediate runtime error after adding a datapoint

```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1029)
	at java.util.ArrayList$Itr.next(ArrayList.java:982)
	at com.patrykandpatrick.vico.core.entry.ChartEntryExtensionsKt.calculateXGcd(ChartEntryExtensions.kt:98)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.getInternalModel(ChartEntryModelProducer.kt:111)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.getInternalModel$default(ChartEntryModelProducer.kt:98)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.getModel(ChartEntryModelProducer.kt:117)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.setEntries$lambda$1$lambda$0(ChartEntryModelProducer.kt:79)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.$r8$lambda$cF6wz2uV3lXuCajKiOZn2aNYLKc(Unknown Source:0)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```
I have also modified `diffAnimationSpec = null` in the chart constructor.

LMK if I should open a new issue for this.

**Comment by subhashisbhowmik** [comment] 2023-09-25 16:20
Looks like I can avoid this by updating the graph like this like I was doing initially:
```
LaunchedEffect(key1 = Unit) {
    while (true) {
        producer.setEntries(viewModel.dataList)
        delay(500)
    }
}
```

I had modified the code to update the graph right after fetching the latest values. What should be the right approach here?

**Comment by patrickmichalik** [comment] 2023-09-25 16:45
Could you check if anything changes when `producer.setEntries(viewModel.dataList)` is replaced with `producer.setEntries(viewModel.dataList.toList())`?

**Comment by subhashisbhowmik** [comment] 2023-09-25 17:41
No, I've tried that already

**Comment by patrickmichalik** [comment] 2023-09-25 20:12
Got it. If so, would you be able to provide a full minimal reproducible example? We’ll have to take a closer look.

**Comment by subhashisbhowmik** [comment] 2023-09-25 20:17
Sure, I'll create another project and get back

**Comment by patrickmichalik** [comment] 2023-09-25 20:36
Thanks!

**Comment by subhashisbhowmik** [comment] 2023-09-26 06:07
Here: https://github.com/subhashisbhowmik/VicoTestApp

The issue is there after running for around 10 seconds on pixel 7 pro emulator

Notice that I'm updating the values asynchronously
```
LaunchedEffect(key1 = Unit) {
                        while (true) {
                            launch (Dispatchers.IO){
                                x += 0.02F
                                viewModel.data.add(FloatEntry(x, sin(x * 2 * PI.toFloat())))
                                while (viewModel.data.size > 3080) viewModel.data.removeFirst()
                                producer.setEntries(viewModel.data.toList())
                            }
                            delay(5)
                        }
                    }
```
This is because my use-case has a callback notifying me when I have a new datapoint, it works fine if I discard the `launch`.

**Comment by subhashisbhowmik** [comment] 2023-09-26 08:34
I was wrong, the error still occurs even in synchronous update, but it just takes a while.

```
                    LaunchedEffect(key1 = Unit) {
                        while (true) {
                            x += 0.02F
                            viewModel.data.add(FloatEntry(x, sin(x * 2 * PI.toFloat())))
                            while (viewModel.data.size > 3080) viewModel.data.removeFirst()
                            producer.setEntries(viewModel.data.toList())

                            delay(5)
                        }
                    }
```

```
FATAL EXCEPTION: pool-2-thread-1
Process: com.test.vicotestapp, PID: 21981
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.patrykandpatrick.vico.core.entry.ChartEntryExtensionsKt.calculateXGcd(ChartEntryExtensions.kt:98)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.getInternalModel(ChartEntryModelProducer.kt:111)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.getInternalModel$default(ChartEntryModelProducer.kt:98)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.getModel(ChartEntryModelProducer.kt:117)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.setEntries$lambda$1$lambda$0(ChartEntryModelProducer.kt:79)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer.$r8$lambda$cF6wz2uV3lXuCajKiOZn2aNYLKc(Unknown Source:0)
	at com.patrykandpatrick.vico.core.entry.ChartEntryModelProducer$$ExternalSyntheticLambda2.run(Unknown Source:4)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by patrickmichalik** [comment] 2023-09-26 11:45
Thank you, @subhashisbhowmik. We’ve determined where the problem lies and are looking into it. The fix will be included in Vico 1.13.0 Alpha 4.

**Comment by subhashisbhowmik** [comment] 2023-09-26 11:49
@patrickmichalik thanks a lot! 
My earlier workaround with updating the graph every 100ms also seems to fail at a few rare occasions. Can you help me with either the ETA for alpha 4 or any other workaround?

**Comment by patrickmichalik** [comment] 2023-09-26 11:59
Since `ChartEntryModelProducer` is at fault here, you could use the `Chart` overload that accepts a `ChartEntryModel`. You can create `ChartEntryModel`s via `entryModelOf`:

```kt
entryModelOf(viewModel.data)
```

Vico 1.13.0 Alpha 3 comes out today. The ETA for version 1.13.0 Alpha 4 is tomorrow or the day after.

**Comment by patrickmichalik** [comment] 2023-09-30 21:38
I wanted to share a quick update. The issue turned out to be more complex than we initially thought, so more time was required to resolve it. We now have a fix, and we plan on releasing Vico 1.13.0 Alpha 4 within 24 hours. Apologies for the delay.

**Comment by subhashisbhowmik** [comment] 2023-10-01 05:26
@patrickmichalik no worries, I appreciate the effort :)

**Comment by patrickmichalik** [comment] 2023-10-01 19:05
[Vico 1.13.0 Alpha 4](https://github.com/patrykandpatrick/vico/releases/tag/v1.13.0-alpha.4) is now available. The problem here was that multiple updates could run at once. `ChartEntryModelProducer#setEntries` processes updates asynchronously, but there was no mutex in place. We’ve introduced an update rejection mechanism and added several new functions, including `ChartEntryModelProducer#setEntriesSuspending`, which is perfect for your use case. Once you’ve updated Vico, please try the following.

```kt
LaunchedEffect(...) {
    withContext(Dispatchers.Default) {
        while (true) {
            ...
            producer.setEntriesSuspending(viewModel.data).await()
            delay(5)
        }
    }
}
```

Please note that this would behave differently if you were to launch a new coroutine for each `setEntriesSuspending` call, similarly to what you did [here](https://github.com/patrykandpatrick/vico/issues/408#issuecomment-1734885884). Since the loop wouldn’t be suspended, an ever-lengthening queue of updates would form, which is highly undesirable. The key takeaway is that, for frequent updates, one should either ensure that they’re not queueing too many updates (which is achieved above by means of `Deferred#await`) or allow overlapping updates to be rejected, an example of which you can find below. In this example, `withContext` is used only because of the infinite loop, and if you were to omit it, there likely wouldn’t be a noticeable performance decrease. This is because `setEntries` launches a coroutine internally, using `Dispatchers.Default` by default.

```kt
LaunchedEffect(...) {
    withContext(Dispatchers.Default) {
        while (true) {
            ...
            producer.setEntries(viewModel.data)
            delay(5)
        }
    }
}
```

While testing this, I noticed that the chart flickers intermittently. This is a separate problem, and we’ve just finished preparing a fix, which will be included in Vico 1.13.0 Alpha 5. I’ll let you know when that’s available. If you have any questions or face any issues, please feel free to let me know.

**Comment by patrickmichalik** [comment] 2023-10-04 20:42
Sounds good. [Vico 1.13.0 Alpha 5](https://github.com/patrykandpatrick/vico/releases/tag/v1.13.0-alpha.5), which resolves the flickering issue, is now rolling out. I enclose a screen recording.

https://github.com/patrykandpatrick/vico/assets/120058021/d712bb25-c5cb-422c-9304-d60878e0b0c9

**Comment by patrickmichalik** [comment] 2023-10-07 15:07
I’ll be removing the “bug” label because we now use discussions for everything but bug reports, making the “bug” label redundant. Please rest assured that this doesn’t change anything about the bug report.

**Comment by subhashisbhowmik** [comment] 2023-10-16 04:13
This works great! But I'm noticing a different issue mentioned in #374

**Comment by patrickmichalik** [comment] 2023-10-16 20:57
I’m glad to hear that the problem described here has been resolved. I believe that by now, the solution to the issue described under #374 has been clarified, but if you have any further questions on that topic, let’s continue our conversation there.

**Comment by patrickmichalik** [comment] 2023-11-19 12:49
[Vico 1.13.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.13.0) is now out, so I’ll be closing this issue. Thanks!

**Closed** 2023-11-19 12:49 UTC
Labels: high priority
