### ISSUE TITLE
Crash after upgrading to 1.11.3

### ISSUE THREAD

**Issue by rezafaraji93** [patrykandpatrick/vico#383] opened 2023-09-02 06:49 UTC
**Describe the bug**
After upgrading to 1.11.3 from 1.11.1 a crash is occurued:
`java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/runtime/PrimitiveSnapshotStateKt`

**Comment by patrickmichalik** [comment] 2023-09-02 07:57
Hello! It looks like you’re using an incompatible Jetpack Compose version. Vico includes the latest release of the Jetpack Compose BOM. Please see #366.

**Comment by EzekielWachira** [comment] 2023-09-03 15:05
Same here

**Comment by patrickmichalik** [comment] 2023-09-12 07:42
I’ll be closing this issue because it’s a duplicate of #366. If a minimal reproducible example showing that this problem stems from a bug in Vico is shared, we’ll reopen issue #366. However, we’ve looked into the matter and are confident that Vico isn’t at fault, as I’ve mentioned [here](https://github.com/patrykandpatrick/vico/issues/366#issuecomment-1704339578).

**Closed by patrickmichalik** 2023-09-12 07:42 UTC
Labels: bug
