### ISSUE TITLE
Crash inside AnimatedVisibility()

### ISSUE THREAD

**Issue by fuadenergyom** [patrykandpatrick/vico#710] opened 2024-05-16 15:06 UTC
### How to reproduce

I searched through closed issues and this was addressed in this issue: https://github.com/patrykandpatrick/vico/issues/200
I have created a CartesianChartHost that works fine inside any layout. However, when put inside an AnimatedVisibility(), it crashes when the visibility becomes true. In the old issue you mentioned it would get fixed in 1.6.5, and I am currently using 2.0.0-alpha.19

How to Reproduce:
Create a CartesianChartHost with CartesianChart with LineCartesianLayer. Use it inside an AnimatedVisibility() block.

### Observed behavior

Crashes as soon as visibility becomes true. coerceIn() method causes the crash, because of 0 value of bounds.height().toInt() (in BaseDynamicShader.kt:43).

### Expected behavior

Normally render the chart, even with initial height of 0.

### Vico version(s)

Latest unstable version

### Android version(s)

Android 14 (Virtual Device)

**Comment by patrickmichalik** [comment] 2024-05-17 10:54
Hello! Thanks for the report. We’ve followed the reproduction instructions and tried several other setups, but unfortunately, we haven’t been able to reproduce the crash. Could you share a minimal reproducible example? A few extra notes:

- The problem reported in issue #200 was resolved in Vico 1.6.5. Something else seems to be happening here.
- At least by default, `AnimatedVisibility` appears to clip its content, not resize it. The `CartesianChartHost`’s height should remain unaffected, and this was the case in our testing.

**Comment by fuadenergyom** [comment] 2024-05-17 11:34
Hey Patrick! Thank you very much for taking the time to look at this. I rolled back to yesterday's version of the app and tried to find what was causing the issue, and I figured it out. This is an extremely specific case: my `AnimatedVisibility` is inside a `Column`, which is inside a `Box`, which is inside another `Column`, and the whole thing is inside the `content: @Composable (PaddingValues) -> Unit` block of `BottomSheetScaffold`. When I use the `PaddingValues` in the parent Column, or the Box that's the only child of it, it would cause this crash. Another thing worth considering is that I measure content's height to determine `sheetPeekHeight` for `BottomSheetScaffold`.
I don't know if you think this is worth addressing or not, but here is the minimal reproduction:

`
BottomSheetScaffold(
...
) { paddingValues ->
            Column(
                Modifier
                    .fillMaxSize()
                    .padding(paddingValues)   // The crash doesn't happen if this is removed.
            ) {
                Box(
                    Modifier
                        .fillMaxWidth()               // We can also put padding(paddingValues) here and it would crash.
                        .background(Color.White)
                        .onGloballyPositioned { coordinates ->
                            val height = with(localDensity) {
                                coordinates.size.height.toDp()
                            }
                            sheetHeight = (screenHeight - height) - 20.dp
                        }
                ) {
                    Column(
                        modifier = Modifier
                            .fillMaxWidth()
                            .padding(horizontal = 20.dp)
                    ) {
                        HomeViewSwitch(                       // This is just to show/hide the chart
                            modifier = Modifier,
                            mapViewSelected = mapViewSelected,
                            onClick = {
                                screenModel.changeHomeScreenView()
                            }
                        )
                        AnimatedVisibility(
                            visible = !mapViewSelected,
                            enter = fadeIn(tween(300)),
                            exit = fadeOut(tween(300))
                        ) {
                            LineChartImpl(                                          // This is a wrapper around `CartesianChartHost`
                                dataPoints = listOf(10f, 20f, 3f, 4f, 6f)
                            )
                        }
                    }
                }
            }
        }
`

**Comment by Gowsky** [comment] 2024-05-22 18:56
Hello @fuadenergyom, please provide a **self-contained** MRE. The code you've shared contains unknown references.

**Comment by Gowsky** [comment] 2024-05-29 17:20
Closing due to no MRE.

**Closed by Gowsky** 2024-05-29 17:20 UTC
Labels: needs information, bug
