### ISSUE TITLE
Duplicated x-axis step with marker for stacked columns with line

### ISSUE THREAD

**Issue by ivaylopenevmg** [patrykandpatrick/vico#975] opened 2024-12-17 14:45 UTC
### How to reproduce

Create a graph with both stacked `ColumnCartesianLayer` and `LineCartesianLayer`.

### Observed behavior

When we move the marker on a graph with both stacked columns and a line we noticed that in some occasions the x-axis step is repeated. In the screenshots bellow we have twice the x value 7. The first step shows the columns values and the second step also with value 7 shows the line value. The issues appears always on for the same x values and it's not random. It doesn't appear when we use columns only or line only.

![Screenshot_20241217_095039 1](https://github.com/user-attachments/assets/04598b48-0d9a-4802-a9e7-cb6222acf4d7)
![Screenshot_20241217_095050 1](https://github.com/user-attachments/assets/e8d2654e-cda1-4677-bc37-7f238a9e016d)

### Expected behavior

The marker should not repeat the same step and show all values fro both stacked columns and lines in the same view.

### Vico version(s)

2.0.0-beta.3

### Android version(s)

15

**Comment by Gowsky** [comment] 2024-12-17 18:13
Hello, @ivaylopenevmg. We weren't able to reproduce the bug using the information you provided. Because of this, and no MRE I'm closing this issue until the MRE is provided.

**Closed by Gowsky** 2024-12-17 18:13 UTC
Labels: bug
