### ISSUE TITLE
Not able to grab a screenshot test of a graph

### ISSUE THREAD

**Issue by aleksandra-krzemien** [patrykandpatrick/vico#537] opened 2024-01-12 17:31 UTC
### How to reproduce

Open project from [here](https://github.com/aleksandra-krzemien/nested-nav-graphs-example/tree/krzemien/compose-tests-with-animations) and run task `recordRoborazziDebug`.

The test being run is `RoborazziTest` and the screenshot can be found in `build/outputs/roborazzi/`

### Observed behavior

I was experimenting with simple screenshot tests with [roborazzi](https://github.com/takahirom/roborazzi), and I noticed that Vico graphs are not being captured by screenshot.

I'm not fully sure if this is an issue with vico, but in the runtime everything is ok, and all other composable components are being screenshoot correctly, it seems like vico issue.
![Zrzut ekranu 2024-01-12 o 18 14 09](https://github.com/patrykandpatrick/vico/assets/101054541/337ea785-4d26-4102-983a-5017484fcda5)

### Expected behavior

I'd expect the graph to be drawn in a similar way it's drawn on the preview
![Zrzut ekranu 2024-01-12 o 18 15 53](https://github.com/patrykandpatrick/vico/assets/101054541/9c3e0362-28af-4cf9-bced-695ee64c531e)

### Vico version(s)

Latest stable version

### Android version(s)

Android 13

**Comment by Gowsky** [comment] 2024-01-12 18:08
Hi @aleksandra-krzemien, I suppose you're using `ChartEntryModelProducer` in your tests. If so, that's the reason. Vico processes data asynchronously, and Roborazzi (or Paparazzi we're using) may not allow Vico to render itself after it processes the data.

To solve this problem, I'd suggest creating `ChartEntryModel` manually, like we do [here](https://github.com/patrykandpatrick/vico/blob/a7b04958223b2af269c38fd1793305665f057008/sample/src/main/java/com/patrykandpatrick/vico/sample/previews/resource/SampleModels.kt) for a chart preview like [this](https://github.com/patrykandpatrick/vico/blob/a7b04958223b2af269c38fd1793305665f057008/sample/src/main/java/com/patrykandpatrick/vico/sample/previews/composables/line/LineCharts.kt) used for [Paparazzi tests](https://github.com/patrykandpatrick/vico/blob/a7b04958223b2af269c38fd1793305665f057008/sample/src/test/kotlin/com/patrykandpatrick/vico/sample/PaparazziTest.kt). I hope that it resolves your problem.

**Comment by patrickmichalik** [comment] 2024-01-13 10:32
Hello! Generally, @Gowsky’s solution would be the simplest approach, but if you’d like to use `ChartEntryModelProducer` here, it should be possible. I’ve taken a look at your code and noticed that you’ve commented out a solution that incorporates `LaunchedEffect` and `setEntriesSuspending`. This should be compatible with screenshot tests, and it works with Paparazzi in the Vico project. Just to confirm, did you face issues with this approach too? (I was unable to test this myself because when I tried to run `recordRoborazziDebug` in your project, I got a relatively cryptic error message about `abc_vector_test`.)

I also wanted to let you know about an issue with your setup. This is unrelated to the test problem, but it’s generally noteworthy. When using `ChartEntryModelProducer`, rather than creating a `ChartEntryModel`, one should create a `ChartEntry` list. I’d suggest using the following and passing the output to `setEntries`.

```kt
entriesOf(*dataPoints)
```

In your current setup, two `ChartEntryModelProducer`s and two `ChartEntryModel`s are created, with the first `ChartEntryModel`’s generation blocking the main thread. The main benefit of `ChartEntryModelProducer` is thus lost. It would be preferable to move the data mapping (`page.dataPoints.map`) off the main thread too.

**Comment by aleksandra-krzemien** [comment] 2024-01-14 20:41
> To solve this problem, I'd suggest creating ChartEntryModel manually

The case is that in my regular project screenshot tests are more wired to the screen setup (fragment, viewModel, etc), so I can't change the UI logic just for the test, because then the test would be pretty much useless.


> you’ve commented out a solution that incorporates LaunchedEffect and setEntriesSuspending

I commented it out because with that approach the composable preview did not show data on the graph, and I figured it might be connected to the screenshot test issue. With regular `setEntries` the preview looks ok. When I use `setEntriesSuspending` (with `LaunchedEffect`) instead of `setEntries` I get the same result - the graph data on the screenshot is not visible.

> I got a relatively cryptic error message about abc_vector_test

That is super strange. AFAICS `abc_vector_test` resource is used in `getDrawable` function, which I'm not using directly anywhere in my example 🤔 Can you paste some stacktrace of this issue?

Also,
thank you for the hint about `ChartEntryModel`. I'm pretty new to compose, so I may not understand everything related to recompositions and stuff.

> In your current setup, two ChartEntryModelProducers and two ChartEntryModels are created

Is this related to the fact that two pager pages are created or is it related to some compose stuff? (sorry for dumb questions, but I want to make sure if I understand the issue correctly)

**Comment by takahirom** [comment] 2024-01-15 01:22
I think you should override the Default Dispatcher in the test to correct the issue. However, I haven't tried this myself.
In the following file, the dispatcher is not specified: https://github.com/aleksandra-krzemien/nested-nav-graphs-example/blob/krzemien/compose-tests-with-animations/app/src/main/java/com/example/navgraphapplication/SecondFragment.kt#L136
Here is the default dispatcher:  https://github.com/patrykandpatrick/vico/blob/v1/vico/core/src/main/java/com/patrykandpatrick/vico/core/entry/ChartEntryModelProducer.kt#L47

**Comment by aleksandra-krzemien** [comment] 2024-01-15 14:03
I got the screenshot tests working using 
```
LaunchedEffect(dataPoints) {
    entryProducer.setEntriesSuspending(entriesOf(*dataPoints)).await()
}
```
and 
```
composeTestRule.waitForIdle()
```
 instead of playing with `composeTestRule.mainClock`

but now I started to observe [this issue](https://github.com/patrykandpatrick/vico/issues/467) again in my regular project (both in runtime and in screenshot tests) - but not in the example repo - so I'm not sure if this is the right approach, but I'm just hitting a bug, or if I still miss something 😅

**Comment by aleksandra-krzemien** [comment] 2024-01-15 16:32
@patrickmichalik as for the drawable exception, it seems that Robolectric's [RNG doesn't work on Windows](https://github.com/robolectric/robolectric/issues/8312), so you'd have to use `@GraphicsMode(GraphicsMode.Mode.LEGACY)` in the `RoborazziTest`.

Thank you for the explanation. About proposed solution, I can confirm that for the example project I linked it works fine. In my regular project I hit `IllegalStateException` pretty much every time when using `withContext(Dispatchers.Default)` and from time to time without it, so probably there is an issue with my setup. There isn't any alpha version of Vico 1 with this issue fixed so I can check if I still get the exception, right?

**Comment by patrickmichalik** [comment] 2024-01-15 16:55
Thanks for the tip, @aleksandra-krzemien! I work on both Windows and macOS, so I’ll keep in mind to use the latter with Roboelectric.

I’m glad the suggested solution works as expected. Regarding the `IllegalStateException` issue, even if the exception occurs frequently, it almost certainly isn’t a problem with your setup. This exception points to an internal synchronization issue, and we’ve identified the cause. There isn’t a Vico 1 alpha with a fix yet, but we’re working on porting the fix from Vico 2 to Vico 1 as we speak, and an alpha will be released as soon as this is done.

**Comment by aleksandra-krzemien** [comment] 2024-01-15 17:23
Ok, so I guess there is nothing more to discuss in this issue for now, and you can close it if you prefer. I'll update to the new Vico version once it's available and check if everything works as expected.

**Comment by patrickmichalik** [comment] 2024-01-15 17:26
Sounds good. I’ll let you know when the update is available. I’m using “Close as not planned” because the issue with screenshot tests turned out not to be a Vico bug.

**Closed by patrickmichalik** 2024-01-15 17:26 UTC

**Comment by patrickmichalik** [comment] 2024-01-17 21:35
The update, [Vico 1.14.0 Alpha 2](https://github.com/patrykandpatrick/vico/releases/tag/v1.14.0-alpha.2), is now available, @aleksandra-krzemien.

**Comment by aleksandra-krzemien** [comment] 2024-01-17 22:51
I can confirm that with this version both my app and my screenshot tests work correctly without any exceptions 🎉

**Comment by patrickmichalik** [comment] 2024-01-18 09:03
I’m glad to hear that!
