### ISSUE TITLE
IllegalStateException CollectionsKt.getRepeating

### ISSUE THREAD

**Issue by sebastian-hoebarth** [patrykandpatrick/vico#948] opened 2024-11-08 16:23 UTC
### How to reproduce

Removing all elements from the chart.

java.lang.IllegalStateException: Cannot get repeated item from empty collection.
                 	at com.patrykandpatrick.vico.core.common.CollectionsKt.getRepeating(Collections.kt:47)
                 	at com.patrykandpatrick.vico.core.cartesian.layer.ColumnCartesianLayer$ColumnProvider$Companion$Series.getWidestSeriesColumn(ColumnCartesianLayer.kt:615)
                 	at com.patrykandpatrick.vico.core.cartesian.layer.ColumnCartesianLayer.getColumnCollectionWidth(ColumnCartesianLayer.kt:417)
                 	at com.patrykandpatrick.vico.core.cartesian.layer.ColumnCartesianLayer.updateHorizontalDimensions(ColumnCartesianLayer.kt:394)
                 	at com.patrykandpatrick.vico.core.cartesian.layer.ColumnCartesianLayer.updateHorizontalDimensions(ColumnCartesianLayer.kt:71)
                 	at com.patrykandpatrick.vico.core.cartesian.CartesianChart$horizontalDimensionUpdateModelAndLayerConsumer$1.invoke(CartesianChart.kt:115)
                 	at com.patrykandpatrick.vico.core.cartesian.CartesianChart.forEachWithLayer(CartesianChart.kt:478)
                 	at com.patrykandpatrick.vico.core.cartesian.CartesianChart.prepare(CartesianChart.kt:213)
                 	at com.patrykandpatrick.vico.compose.cartesian.CartesianChartHostKt.CartesianChartHostImpl$lambda$23$lambda$22(CartesianChartHost.kt:195)
                 	at com.patrykandpatrick.vico.compose.cartesian.CartesianChartHostKt.$r8$lambda$aQQKwZOn9huYyaTRo_AvgGCegn8(Unknown Source:0)
                 	at com.patrykandpatrick.vico.compose.cartesian.CartesianChartHostKt$$ExternalSyntheticLambda5.invoke(D8$$SyntheticClass:0)
                 	at androidx.compose.ui.draw.DrawBackgroundModifier.draw(DrawModifier.kt:127)

### Observed behavior

Sometimes not always happening.

### Expected behavior

Not crashing.

### Vico version(s)

2.0.0-beta.2

### Android version(s)

Android 15

**Comment by Gowsky** [comment] 2024-11-08 19:55
Hello, @sebastian-hoebarth. This suggests that you're performing dynamic setup incorrectly, disregarding the fact that `Transaction`s are handled asynchronously. Specifically, it seems like you're directly using the data from the latest `Transaction` to create a column list, which is then passed to `ColumnProvider.series`. As described [in the wiki](https://patrykandpatrick.com/vico/wiki/cartesian-charts/data/#asynchrony-and-extras), such usage is incorrect.

If you need to update the column list in sync with the data, you should implement `ColumnProvider` and perform these updates based on the information passed to `getColumn`. This will provide proper synchronization. You'll most likely want to use extras. If you describe your use case, we can suggest an approach.

I'm closing this issue because the crash is a result of incorrect usage, not a bug.

**Closed by Gowsky** 2024-11-08 19:55 UTC
Labels: bug
