### ISSUE TITLE
onHidden not always called when scrubbing

### ISSUE THREAD

**Issue by spectrl** [patrykandpatrick/vico#971] opened 2024-12-14 11:42 UTC
### How to reproduce

Swipe/scrub (quite quickly) on the chart and observe that `onHidden` is not always called in the `CartesianMarkerVisibilityListener`.

### Observed behavior

After a swipe on the chart, although onShown is called, and the marker and guideline are drawn, after lifting up your finger onHidden is often not called. The marker and guideline do correctly disappear though.

### Expected behavior

onHidden should be called every time the marker and guideline go away – when I lift my finger from the chart.

### Vico version(s)

2.0.0-beta.3

### Android version(s)

Android 15

### Additional information

I have scroll and zoom disabled if that helps.

**Comment by spectrl** [comment] 2024-12-14 11:43
I have scroll and zoom disabled if that helps.

**Comment by Gowsky** [comment] 2024-12-14 16:10
Hello, @spectrl. We weren't able to reproduce the bug using the information you provided. Because of this, and no MRE I'm closing this issue until the MRE is provided.

**Closed by Gowsky** 2024-12-14 16:10 UTC
Labels: bug

**Comment by spectrl** [comment] 2024-12-16 14:44
As I was preparing a minimal example for you, I noticed I couldn't reproduce the bug I described. Turned out to be an issue with my implementation – still not exactly sure what was happening but it seemed like the chart was being recomposed as a result of some updates I was making in `onUpdated` and so some `onHidden` callbacks were being dropped (even though my listener instance was remembered) _I think_...
