### ISSUE TITLE
"Each entry’s x value must be a multiple of the x step."  this dialog happened when I used 2 entries

### ISSUE THREAD

**Issue by yacht256** [patrykandpatrick/vico#417] opened 2023-10-05 11:22 UTC
![Screenshot 2566-10-05 at 18 12 10](https://github.com/patrykandpatrick/vico/assets/72908624/884f41dc-b250-43ae-8764-3c23ab9f70a4)
this is my first entry which has been working normally 
![Screenshot 2566-10-05 at 18 16 10](https://github.com/patrykandpatrick/vico/assets/72908624/124af1dc-5c84-4757-9bd4-247b5c3f021a)

after adding another entry it make  xspacing < 0 How can I fixed it or How can I change the Xstep  
![Screenshot 2566-10-05 at 18 16 17](https://github.com/patrykandpatrick/vico/assets/72908624/21847da2-21f2-4d64-b391-6c2f70806451)

**Comment by patrickmichalik** [comment] 2023-10-05 18:06
Hello! Could you provide some more context or, preferably, a minimal reproducible example? I’ve created a chart with a data set matching what’s shown in your first screenshot, and it works as expected. Take a look:

<img src="https://github.com/patrykandpatrick/vico/assets/120058021/ff766e58-161b-479f-b6ec-09e978d81ec3" width="720" />

To answer your question about changing the _x_ step, you can do so via `getXStep`, which is a parameter of the `Chart` composable function and a field of `BaseChartView` (and, by extension, `ChartView` and `ComposedChartView`).

**Comment by yacht256** [comment] 2023-10-05 18:52
<img width="988" alt="Screenshot 2566-10-06 at 01 48 04" src="https://github.com/patrykandpatrick/vico/assets/72908624/c39927f4-2997-4c88-9301-89bf1eb93311">
I want to use a stacked column in the chart following this code and I found that when I use 2 entries  it makes error from the topic

**Comment by patrickmichalik** [comment] 2023-10-06 15:24
Got it. Could you please share the code that creates the chart?

**Comment by yacht256** [comment] 2023-10-06 15:28
<img width="900" alt="Screenshot 2566-10-06 at 22 27 07" src="https://github.com/patrykandpatrick/vico/assets/72908624/ba40f3e4-3d0e-4df7-aa79-4e8b40da05c5">
thank you for your reply So I set it to ChartView

**Comment by patrickmichalik** [comment] 2023-10-06 15:44
Thank you. Two questions:

1. Does the issue persist if you remove everything except `setModel(chartEntryModel)` from the lambda?

    ```kt
    binding.chartView.apply { setModel(chartEntryModel) }
    ```
    If so, does the crash continue to occur when `setModel(chartEntryModel)` is replaced with `setModel(entryModelOf(19608 to 1, 19629 to 1))`?
4. What version of Vico are you using?

**Comment by yacht256** [comment] 2023-10-06 15:58
1 when I use only binding.chartView.apply { setModel(chartEntryModel) } in my code. It doesn't work. But if I use your data it works normally 
2.![image](https://github.com/patrykandpatrick/vico/assets/72908624/58a01 ce7-96b2-4f88-aeae-8a48d1877b1f)

**Comment by patrickmichalik** [comment] 2023-10-07 09:47
Cheers! This looks like a bug. We’ll release a fix soon, and in the meantime, you can override the _x_ step by adding `getXStep = { 1f }` to the `apply` lambda.

**Comment by patrickmichalik** [comment] 2023-10-07 15:07
I’ll be removing the “bug” label because we now use discussions for everything but bug reports, making the “bug” label redundant. Please rest assured that this doesn’t change anything about the bug report.

**Comment by patrickmichalik** [comment] 2023-10-11 12:29
[Vico 1.13.0 Alpha 6](https://github.com/patrykandpatrick/vico/releases/tag/v1.13.0-alpha.6) fixes this. We’ll close this issue once Vico 1.13.0 is stable. Cheers!

**Comment by RoustamManookian** [comment] 2023-11-09 11:18
Hi,
Is there a way to show x values that are not "multiple of x steps"?
Even in your sample code in wiki/axis there is no value for "3 Jul" but it is showing.
![2023-11-09_131157](https://github.com/patrykandpatrick/vico/assets/75514218/9a2ff1c6-1212-4007-b2d0-beb3b273959f)

**Comment by patrickmichalik** [comment] 2023-11-15 18:51
In `LineChart`s, not all _x_ values have to be multiples of the _x_ step, @RoustamManookian. However, to achieve the result you’ve described, rather than using _x_ values that aren’t multiples of the _x_ step, one should use _x_ values that are less closely tied to the data. Please consider the following.

```kt
val dates = listOf("2022-07-01", "2022-07-02", "2022-07-04").map(LocalDate::parse)
val yValues = listOf(2f, 6f, 4f)
val chartEntryModel = entryModelOf(yValues.mapIndexed(::entryOf))
val dateTimeFormatter = DateTimeFormatter.ofPattern("d MMM")
val horizontalAxisValueFormatter =
    AxisValueFormatter<AxisPosition.Horizontal> { x, _ -> dates[x.toInt()].format(dateTimeFormatter) }
```

<img src="https://github.com/patrykandpatrick/vico/assets/120058021/8e7b5bd0-250f-4ca2-9090-8ec8ca5647ca" width="720" />

**Comment by patrickmichalik** [comment] 2023-11-19 12:48
[Vico 1.13.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.13.0) is now out, so I’ll be closing this issue. Thanks!

**Closed** 2023-11-19 12:48 UTC
Labels: high priority
