### ISSUE TITLE
Order of persistent marker is ignored

### ISSUE THREAD

**Issue by fax-sma** [patrykandpatrick/vico#858] opened 2024-08-21 14:02 UTC
### How to reproduce

Add two persistent marker to one chart that overlap.

### Observed behavior

The order of the markers is not preserved from the original map. 

### Expected behavior

I would like to control the order of the markers by the order of the map I put into the chart.

### Vico version(s)

1.15.0

### Android version(s)

All

### Additional information

I have looked down into `BasicChart` and found that the holder for persistent markers is a `HashMap`. By changing it to a `LinkedHashMap` the expected behavior could be achieved.

**Comment by Gowsky** [comment] 2024-09-14 18:59
This has been addressed in Vico 2 — the order of persistent markers is now preserved. However, this is an enhancement, not a bug fix, since order preservation was never suggested. Vico 1 receives only backward-compatible bug fixes, so this change won’t be ported to it. Please consider updating to Vico 2.

**Comment by fax-sma** [comment] 2024-09-16 08:29
> However, this is an enhancement, not a bug fix

In my opinion this is a bug because it leads to unwanted behavior. You can't predict which marker will be rendered first. So it can clearly break a fully functional UI. 

> Please consider updating to Vico 2.

We may consider this in the future but since there are breaking changes nearly every alpha-release we won't do that as of now.

**Comment by Gowsky** [comment] 2024-09-17 18:15
@fax-sma, a bug causes **incorrect** behavior. There should be a reasonably objective standard by which it's an error. The lack of order preservation alone isn't categorically incorrect, even if creates an undesirable limitation. A consumer can still depend on behavior that is unwanted in certain cases, and a change in this behavior would be a breaking change for such a consumer.

However, it turns out that persistent markers are ordered unpredictably in Vico 1. They may be ordered by _x_ value, but they aren't always. This unpredictability does constitute a bug. It also means that a consumer cannot reasonably depend on the current behavior.

To fix the bug, we have to introduce some kind of ordering, and keeping the order in which the consumer added the markers is the best choice. Therefore, we will be making this change to Vico 1, and I'm reopening the issue.

**Comment by Gowsky** [comment] 2024-10-13 10:58
Hello, Vico [1.16.0-alpha.1](https://patrykandpatrick.com/vico/releases/1.16.0-alpha.1) addresses this. Cheers!

**Comment by Gowsky** [comment] 2024-12-06 19:55
Vico [1.16.0](https://github.com/patrykandpatrick/vico/releases/tag/v1.16.0) is now available.

**Closed** 2024-12-06 19:56 UTC
Labels: done in beta, bug
