### ISSUE TITLE
only the middle index of the chart does not change the font size and color.

### ISSUE THREAD

**Issue by Minoyam** [patrykandpatrick/vico#390] opened 2023-09-05 02:24 UTC
**Describe the bug**
I checked #381 and changed it to Vico 1.11.3, but it still happens.
only the middle index of the chart does not change the font size and color.

**Module**

- [x] `compose`
- [ ] `views`
- [ ] `compose-m2`
- [ ] `compose-m3`
- [x] `core` (select if none of the above apply)

**To reproduce**
Steps to reproduce the behavior.
`object CustomMarkerLabelFormatter : MarkerLabelFormatter {

    private const val PATTERN = "내 수치\n%.0fmg/dL"

    override fun getLabel(
        markedEntries: List<Marker.EntryModel>,
        chartValues: ChartValues,
    ): CharSequence = markedEntries.transformToSpannable(
        prefix = if (markedEntries.size > 1) PATTERN.format(markedEntries.sumOf { it.entry.y }) + " (" else "",
        postfix = if (markedEntries.size > 1) ")" else "",
        separator = "; ",
    ) { model ->
        appendCompat(
            PATTERN.format(model.entry.y),
            ForegroundColorSpan(Black.toArgb()),
            Spannable.SPAN_EXCLUSIVE_EXCLUSIVE,
        ).apply {
            setSpan(AbsoluteSizeSpan(24, true), 0, 4, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
            setSpan(ForegroundColorSpan(Gray100.toArgb()), 0, 4, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
        }
    }
}`

**Expected behavior**
The letter "내 수치" should be changed to size 24, color Gray 100.
However, only the middle index of the chart does not change the font size and color.

**Screenshots**
![edited_Screenshot_20230905_111609_HDEC_20230905_111714](https://github.com/patrykandpatrick/vico/assets/49590389/84e8422e-b4b5-4a1c-90a0-5785044eae77)
![edited_Screenshot_20230905_111611_HDEC_20230905_111658](https://github.com/patrykandpatrick/vico/assets/49590389/332b946f-6362-4015-8a5e-25de1106094d)
![edited_Screenshot_20230905_111607_HDEC_20230905_111727](https://github.com/patrykandpatrick/vico/assets/49590389/3e1eb67e-2cfc-4919-bbc9-975111c0cff9)

**Android versions**
Android 13

**Comment by patrickmichalik** [comment] 2023-09-05 10:29
Hello! Thanks for the report. Could you please describe how to reproduce the problem? A minimal reproducible example would work too. Without knowing how to reproduce the bug, we are, unfortunately, unable to investigate and resolve it. I’ve followed the steps listed by @p-fischer in #381 and applied your `MarkerLabelFormatter`, but no unexpected behavior can be observed.

**Comment by Minoyam** [comment] 2023-09-06 09:57
**MarkerLabelFormatter**

`object CustomMarkerLabelFormatter : MarkerLabelFormatter {

    private const val PATTERN = "내 수치\n%.0fmg/dL"

    override fun getLabel(
        markedEntries: List<Marker.EntryModel>,
        chartValues: ChartValues,
    ): CharSequence = markedEntries.transformToSpannable(
        prefix = if (markedEntries.size > 1) PATTERN.format(markedEntries.sumOf { it.entry.y }) + " (" else "",
        postfix = if (markedEntries.size > 1) ")" else "",
        separator = "; ",
    ) { model ->
        appendCompat(
            PATTERN.format(model.entry.y),
            ForegroundColorSpan(Black.toArgb()),
            Spannable.SPAN_EXCLUSIVE_EXCLUSIVE,
        ).apply {
            setSpan(AbsoluteSizeSpan(24, true), 0, 4, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
            setSpan(ForegroundColorSpan(Gray100.toArgb()), 0, 4, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE)
        }
    }
}`

**LineChart**

`@Composable
fun LineChart(chartEntryModel: ChartEntryModel) {
    val days = stringArrayResource(R.array.day_of_the_week)
    val marker = rememberMarker()
    Chart(
        modifier = Modifier
            .fillMaxWidth()
            .height(300.dp),
        isZoomEnabled = false,
        chart = lineChart(
            axisValuesOverrider = AxisValuesOverrider.fixed(
                minX = 0f,
                maxY = 220f,
            ),
        ),
        marker = marker,
        model = chartEntryModel,
        startAxis = rememberStartAxis(
            label = textComponent(
                color = Gray100,
                textSize = 20.sp,
                padding = dimensionsOf(horizontal = 4.dp, vertical = 2.dp),
            ),
            axis = null,
            tick = null,
            guideline = LineComponent(
                color = Gray200Op50.toArgb(),
                thicknessDp = 1.dp.value,
            ),
            valueFormatter = { value, _ ->
                if (value.isFinite() && value.roundToInt().toFloat() == value) value.roundToInt().toString() else ""
            },
            horizontalLabelPosition = VerticalAxis.HorizontalLabelPosition.Outside
        ),
        bottomAxis = rememberBottomAxis(
            label = textComponent(
                color = Gray100,
                textSize = 20.sp,
                padding = dimensionsOf(horizontal = 4.dp, vertical = 12.dp),
            ),
            tick = null,
            guideline = null,
            axis = null,
            valueFormatter = { value, _ ->
                days[value.toInt()]
            })
    )
}`

**Marker**

`@Composable
internal fun rememberMarker(): Marker {
    val labelBackgroundColor = White
    val labelBackground = remember(labelBackgroundColor) {
        ShapeComponent(labelBackgroundShape, labelBackgroundColor.toArgb())
    }
    val label = textComponent(
        color = Black,
        textSize = 30.sp,
        background = labelBackground,
        lineCount = LABEL_LINE_COUNT,
        padding = labelPadding,
        typeface = Typeface.DEFAULT_BOLD
    )
    val indicatorInnerComponent = shapeComponent(Shapes.pillShape, White)
    val indicatorCenterComponent = shapeComponent(Shapes.pillShape, White)
    val indicatorOuterComponent = shapeComponent(Shapes.pillShape, White)
    val indicator = overlayingComponent(
        outer = indicatorOuterComponent,
        inner = overlayingComponent(
            outer = indicatorCenterComponent,
            inner = indicatorInnerComponent,
            innerPaddingAll = indicatorInnerAndCenterComponentPaddingValue,
        ),
        innerPaddingAll = indicatorCenterAndOuterComponentPaddingValue,
    )
    return remember(label, indicator) {
        object : MarkerComponent(label, indicator, null) {
            init {
                indicatorSizeDp = INDICATOR_SIZE_DP
                onApplyEntryColor = { entryColor ->
                    indicatorOuterComponent.color = entryColor.copyColor(INDICATOR_OUTER_COMPONENT_ALPHA)
                    with(indicatorCenterComponent) {
                        color = entryColor
                    }
                }
                labelFormatter = CustomMarkerLabelFormatter
            }

            override fun getInsets(
                context: MeasureContext,
                outInsets: Insets,
                horizontalDimensions: HorizontalDimensions,
            ) {
                outInsets.top = label.getHeight(context)
            }
        }
    }
}

private const val LABEL_LINE_COUNT = 2
private const val INDICATOR_SIZE_DP = 40f
private const val INDICATOR_OUTER_COMPONENT_ALPHA = 0

private val labelBackgroundShape = MarkerCorneredShape(Corner.Relative(20, RoundedCornerTreatment))
private val labelPadding = dimensionsOf(start = 24.dp, end = 24.dp, bottom = 16.dp)
private val indicatorInnerAndCenterComponentPaddingValue = 5.dp
private val indicatorCenterAndOuterComponentPaddingValue = 10.dp`

like that code.

If you need anything else, feel free to comment

**Comment by Minoyam** [comment] 2023-09-06 10:01
**LineChart**

```
@Composable
fun LineChart(chartEntryModel: ChartEntryModel) {
    val days = stringArrayResource(R.array.day_of_the_week)
    val marker = rememberMarker()
    Chart(
        modifier = Modifier
            .fillMaxWidth()
            .height(300.dp),
        isZoomEnabled = false,
        chart = lineChart(
            axisValuesOverrider = AxisValuesOverrider.fixed(
                minX = 0f,
                maxY = 220f,
            ),
        ),
        marker = marker,
        model = chartEntryModel,
        startAxis = rememberStartAxis(
            label = textComponent(
                color = Gray100,
                textSize = 20.sp,
                padding = dimensionsOf(horizontal = 4.dp, vertical = 2.dp),
            ),
            axis = null,
            tick = null,
            guideline = LineComponent(
                color = Gray200Op50.toArgb(),
                thicknessDp = 1.dp.value,
            ),
            valueFormatter = { value, _ ->
                if (value.isFinite() && value.roundToInt().toFloat() == value) value.roundToInt().toString() else ""
            },
            horizontalLabelPosition = VerticalAxis.HorizontalLabelPosition.Outside
        ),
        bottomAxis = rememberBottomAxis(
            label = textComponent(
                color = Gray100,
                textSize = 20.sp,
                padding = dimensionsOf(horizontal = 4.dp, vertical = 12.dp),
            ),
            tick = null,
            guideline = null,
            axis = null,
            valueFormatter = { value, _ ->
                days[value.toInt()]
            })
    )
}
````

**Comment by Minoyam** [comment] 2023-09-06 10:01
**Marker**
```

`@Composable
internal fun rememberMarker(): Marker {
    val labelBackgroundColor = White
    val labelBackground = remember(labelBackgroundColor) {
        ShapeComponent(labelBackgroundShape, labelBackgroundColor.toArgb())
    }
    val label = textComponent(
        color = Black,
        textSize = 30.sp,
        background = labelBackground,
        lineCount = LABEL_LINE_COUNT,
        padding = labelPadding,
        typeface = Typeface.DEFAULT_BOLD
    )
    val indicatorInnerComponent = shapeComponent(Shapes.pillShape, White)
    val indicatorCenterComponent = shapeComponent(Shapes.pillShape, White)
    val indicatorOuterComponent = shapeComponent(Shapes.pillShape, White)
    val indicator = overlayingComponent(
        outer = indicatorOuterComponent,
        inner = overlayingComponent(
            outer = indicatorCenterComponent,
            inner = indicatorInnerComponent,
            innerPaddingAll = indicatorInnerAndCenterComponentPaddingValue,
        ),
        innerPaddingAll = indicatorCenterAndOuterComponentPaddingValue,
    )
    return remember(label, indicator) {
        object : MarkerComponent(label, indicator, null) {
            init {
                indicatorSizeDp = INDICATOR_SIZE_DP
                onApplyEntryColor = { entryColor ->
                    indicatorOuterComponent.color = entryColor.copyColor(INDICATOR_OUTER_COMPONENT_ALPHA)
                    with(indicatorCenterComponent) {
                        color = entryColor
                    }
                }
                labelFormatter = CustomMarkerLabelFormatter
            }

            override fun getInsets(
                context: MeasureContext,
                outInsets: Insets,
                horizontalDimensions: HorizontalDimensions,
            ) {
                outInsets.top = label.getHeight(context)
            }
        }
    }
}

private const val LABEL_LINE_COUNT = 2
private const val INDICATOR_SIZE_DP = 40f
private const val INDICATOR_OUTER_COMPONENT_ALPHA = 0

private val labelBackgroundShape = MarkerCorneredShape(Corner.Relative(20, RoundedCornerTreatment))
private val labelPadding = dimensionsOf(start = 24.dp, end = 24.dp, bottom = 16.dp)
private val indicatorInnerAndCenterComponentPaddingValue = 5.dp
private val indicatorCenterAndOuterComponentPaddingValue = 10.dp`

```

**Comment by Minoyam** [comment] 2023-09-06 10:01
like that code.

If you need anything else, feel free to comment

**Comment by patrickmichalik** [comment] 2023-09-06 13:01
Thank you, @Minoyam, but please keep in mind that a minimal reproducible example should be self-contained. In the code provided, there are unresolved references and no imports. Please see [here](https://vercel.com/guides/creating-a-minimal-reproducible-example) for information on what is understood by “minimal reproducible example.” In this case, there’s no need to create a full project. I suggest putting everything in a single file and sharing the file here. Please ensure that there’s a composable function annotated with `@Preview` that we can run.

**Comment by patrickmichalik** [comment] 2023-09-12 07:36
Because, for the reasons described above, this bug report is incomplete and cannot be addressed, I’ll be closing the issue. Please feel free to share a minimal reproducible example and reopen the issue. Cheers!

**Closed by patrickmichalik** 2023-09-12 07:36 UTC
Labels: bug
